# -- Site Configuration --
# Refer to the theme docs for more details about each of these parameters.
# https://blowfish.page/docs/getting-started/

theme = "blowfish"
baseURL = "https://www.gustavocaso.dev/"
defaultContentLanguage = "en"

# pluralizeListTitles = "true" # hugo function useful for non-english languages, find out more in  https://gohugo.io/getting-started/configuration/#pluralizelisttitles

enableRobotsTXT = true
pagination.pagerSize = 10
summaryLength = 30

buildDrafts = false
buildFuture = false

googleAnalytics = "G-6G4EQ6NHTS"

[imaging]
anchor = 'Center'

[taxonomies]
tag = "tags"

[sitemap]
changefreq = 'daily'
filename = 'sitemap.xml'
priority = 0.5

[outputs]
home = ["HTML", "RSS", "JSON"]

[related]
threshold = 0
toLower = false

[[related.indices]]
name = "tags"
weight = 100

[[related.indices]]
applyFilter = false
name = 'fragmentrefs'
type = 'fragments'
weight = 10

[caches]
[caches.images]
dir = ':cacheDir/images'
